"""Command-line interface: ``p2p``.

Three subcommands:

  p2p run "<prompt>"          # prompt -> LLM -> reward -> PPO -> video
  p2p generate "<prompt>"     # prompt -> LLM, print spec, no training
  p2p train-spec <path>       # train from a JSON RewardSpec, skip LLM

Hyperparameters are fixed per env (see ``train/config.py``). The CLI
exposes only what the user needs to drive the demo: the env, the
prompt, the training budget, the seed, the provider/model, and where
artifacts go.

Provider is chosen explicitly via ``--provider``:
- ``anthropic`` (default): Claude API. Needs ``ANTHROPIC_API_KEY``.
- ``gemini``: Google Gemini API. Needs ``GEMINI_API_KEY`` (or
  ``GOOGLE_API_KEY``) and the ``google-genai`` package.
- ``local``: HuggingFace causal-LM running on the local machine. Needs
  the ``[local]`` extras (transformers, accelerate, bitsandbytes) and a
  GPU big enough for the chosen model. Use this on Colab when the
  runtime is an A100/L4.
"""

from __future__ import annotations

import dataclasses
import json
import sys
from pathlib import Path
from typing import Annotated, Literal

import tyro

from prompt_to_policy import envs
from prompt_to_policy.llm import (
    DEFAULT_GEMINI_MODEL,
    DEFAULT_LOCAL_MODEL,
    DEFAULT_MODEL,
    DEFAULT_QUANTIZATION,
    BaseRewardClient,
    GeminiRewardClient,
    LLMRewardClient,
    LocalLLMRewardClient,
)
from prompt_to_policy.reward import RewardSpec
from prompt_to_policy.train import PPO_CONFIGS, train

DEFAULT_CACHE_DIR = "examples/cached_responses"

EnvName = Literal["halfcheetah", "hopper", "ant"]
Provider = Literal["anthropic", "gemini", "local"]
Quantization = Literal["4bit", "8bit", "none"]


def _resolve_timesteps(env: str, timesteps: int | None, quick: bool) -> int:
    config = PPO_CONFIGS[env]
    if timesteps is not None:
        return timesteps
    if quick:
        return config.quick_timesteps
    return config.total_timesteps


def _resolve_model(provider: Provider, model: str | None) -> str:
    if model is not None:
        return model
    if provider == "local":
        return DEFAULT_LOCAL_MODEL
    if provider == "gemini":
        return DEFAULT_GEMINI_MODEL
    return DEFAULT_MODEL


def _build_client(
    env: str,
    provider: Provider,
    model: str,
    cache_dir: str | None,
    quantization: Quantization,
) -> BaseRewardClient:
    cache = cache_dir if cache_dir else None
    spec = envs.get(env)
    if provider == "anthropic":
        return LLMRewardClient(
            feature_docs=spec.feature_docs,
            model=model,
            cache_dir=cache,
            build_prompt=spec.build_system_prompt,
            env_name=env,
        )
    if provider == "gemini":
        return GeminiRewardClient(
            feature_docs=spec.feature_docs,
            model=model,
            cache_dir=cache,
            build_prompt=spec.build_system_prompt,
            env_name=env,
        )
    if provider == "local":
        return LocalLLMRewardClient(
            feature_docs=spec.feature_docs,
            model_id=model,
            cache_dir=cache,
            quantization=quantization,
            build_prompt=spec.build_system_prompt,
            env_name=env,
        )
    raise ValueError(f"unknown provider: {provider}")


@dataclasses.dataclass
class Run:
    """Generate a reward from a prompt and train a policy end-to-end."""

    prompt: Annotated[str, tyro.conf.Positional]
    """Natural-language description of the desired behavior."""

    env: EnvName = "halfcheetah"
    """Which env to train: 'halfcheetah', 'hopper', or 'ant'."""

    timesteps: int | None = None
    """Total training timesteps. Defaults to env-specific budget; --quick uses the quick budget."""

    quick: bool = False
    """Use the per-env quick development budget. Ignored if --timesteps is set explicitly."""

    seed: int = 0
    """Random seed."""

    provider: Provider = "anthropic"
    """Reward-generation backend: 'anthropic', 'gemini', or 'local'."""

    model: str | None = None
    """Model id. Default depends on --provider."""

    quantization: Quantization = DEFAULT_QUANTIZATION
    """Quantization for --provider local: '4bit' (T4-friendly), '8bit', or 'none'."""

    cache_dir: str | None = DEFAULT_CACHE_DIR
    """Directory for cached LLM responses. Pass an empty string to disable caching."""

    force_refresh: bool = False
    """Bypass the cache for this prompt and re-call the LLM."""

    run_dir: str | None = None
    """Directory for this run's artifacts. Defaults to runs/<auto-generated id>."""

    no_video: bool = False
    """Skip rollout video rendering (useful for headless runs without an OpenGL backend)."""

    progress_bar: bool = False
    """Show a tqdm progress bar during training (requires the rich/tqdm extra)."""


@dataclasses.dataclass
class Generate:
    """Call the LLM for a reward spec and print it. No training."""

    prompt: Annotated[str, tyro.conf.Positional]
    """Natural-language description of the desired behavior."""

    env: EnvName = "halfcheetah"
    """Which env's feature registry to use: 'halfcheetah', 'hopper', or 'ant'."""

    provider: Provider = "anthropic"
    """Reward-generation backend: 'anthropic', 'gemini', or 'local'."""

    model: str | None = None
    """Model id. Default depends on --provider."""

    quantization: Quantization = DEFAULT_QUANTIZATION
    """Quantization for --provider local: '4bit', '8bit', or 'none'."""

    cache_dir: str | None = DEFAULT_CACHE_DIR
    """Directory for cached LLM responses."""

    force_refresh: bool = False
    """Bypass the cache for this prompt."""


@dataclasses.dataclass
class TrainSpec:
    """Train a policy from a hand-written or pre-generated reward spec.

    Useful for offline reproductions and for the post's hand-written
    baselines without burning API spend.
    """

    spec: Annotated[Path, tyro.conf.Positional]
    """Path to a JSON file matching the RewardSpec schema."""

    env: EnvName = "halfcheetah"
    """Which env to train: 'halfcheetah', 'hopper', or 'ant'."""

    prompt: str = "(no prompt — spec from file)"
    """Prompt string to record in summary.json. Has no effect on training."""

    timesteps: int | None = None
    """Total training timesteps. Defaults to env-specific budget; --quick uses the quick budget."""

    quick: bool = False
    """Use the per-env quick budget."""

    seed: int = 0
    """Random seed."""

    run_dir: str | None = None
    """Directory for this run's artifacts."""

    no_video: bool = False
    """Skip rollout video rendering."""

    progress_bar: bool = False
    """Show a tqdm progress bar during training."""


Command = Run | Generate | TrainSpec


def _do_generate(cmd: Generate) -> int:
    model = _resolve_model(cmd.provider, cmd.model)
    client = _build_client(cmd.env, cmd.provider, model, cmd.cache_dir, cmd.quantization)
    gen = client.generate(cmd.prompt, force_refresh=cmd.force_refresh)
    payload = {
        "prompt": cmd.prompt,
        "env": cmd.env,
        "provider": cmd.provider,
        "model": gen.model,
        "cached": gen.cached,
        "cache_key": gen.cache_key,
        "spec": gen.spec.model_dump(),
        "usage": gen.usage,
        "estimated_cost_usd": gen.estimated_cost_usd,
    }
    print(json.dumps(payload, indent=2))
    return 0


def _do_run(cmd: Run) -> int:
    timesteps = _resolve_timesteps(cmd.env, cmd.timesteps, cmd.quick)
    model = _resolve_model(cmd.provider, cmd.model)
    client = _build_client(cmd.env, cmd.provider, model, cmd.cache_dir, cmd.quantization)

    print(f"env       : {cmd.env}", file=sys.stderr)
    print(f"prompt    : {cmd.prompt!r}", file=sys.stderr)
    print(f"provider  : {cmd.provider} ({model})", file=sys.stderr)
    gen = client.generate(cmd.prompt, force_refresh=cmd.force_refresh)
    print(f"  cached  : {gen.cached}", file=sys.stderr)
    print(f"  cost    : ${gen.estimated_cost_usd:.4f}", file=sys.stderr)
    print(f"  spec    : {gen.spec.model_dump_json()}", file=sys.stderr)
    print(file=sys.stderr)
    print(f"training  : {timesteps} timesteps, seed={cmd.seed}", file=sys.stderr)

    result = train(
        spec=gen.spec,
        prompt=cmd.prompt,
        env=cmd.env,
        timesteps=timesteps,
        run_dir=Path(cmd.run_dir) if cmd.run_dir else None,
        seed=cmd.seed,
        record_video=not cmd.no_video,
        progress_bar=cmd.progress_bar,
    )

    print(f"\ndone in {result.train_seconds:.1f}s", file=sys.stderr)
    print(f"  final_mean_return : {result.final_mean_return:.2f}", file=sys.stderr)
    print(f"  final_mean_length : {result.final_mean_length:.0f}", file=sys.stderr)
    print(f"  run_dir           : {result.run_dir}", file=sys.stderr)
    print(f"  video             : {result.video_path}", file=sys.stderr)
    print(f"  summary           : {result.summary_path}", file=sys.stderr)
    return 0


def _do_train_spec(cmd: TrainSpec) -> int:
    timesteps = _resolve_timesteps(cmd.env, cmd.timesteps, cmd.quick)

    spec_text = cmd.spec.read_text()
    spec = RewardSpec.model_validate_json(spec_text)

    print(f"env       : {cmd.env}", file=sys.stderr)
    print(f"spec      : {cmd.spec}", file=sys.stderr)
    print(f"prompt    : {cmd.prompt!r}", file=sys.stderr)
    print(f"training  : {timesteps} timesteps, seed={cmd.seed}", file=sys.stderr)

    result = train(
        spec=spec,
        prompt=cmd.prompt,
        env=cmd.env,
        timesteps=timesteps,
        run_dir=Path(cmd.run_dir) if cmd.run_dir else None,
        seed=cmd.seed,
        record_video=not cmd.no_video,
        progress_bar=cmd.progress_bar,
    )

    print(f"\ndone in {result.train_seconds:.1f}s", file=sys.stderr)
    print(f"  final_mean_return : {result.final_mean_return:.2f}", file=sys.stderr)
    print(f"  final_mean_length : {result.final_mean_length:.0f}", file=sys.stderr)
    print(f"  run_dir           : {result.run_dir}", file=sys.stderr)
    print(f"  video             : {result.video_path}", file=sys.stderr)
    print(f"  summary           : {result.summary_path}", file=sys.stderr)
    return 0


def dispatch(cmd: Command) -> int:
    if isinstance(cmd, Run):
        return _do_run(cmd)
    if isinstance(cmd, Generate):
        return _do_generate(cmd)
    if isinstance(cmd, TrainSpec):
        return _do_train_spec(cmd)
    raise TypeError(f"unknown command: {type(cmd).__name__}")


def main(args: list[str] | None = None) -> int:
    cmd = tyro.cli(Command, args=args)
    return dispatch(cmd)


if __name__ == "__main__":
    raise SystemExit(main())
