"""Command-line interface: ``p2p``.

Three subcommands:

  p2p run "<prompt>"          # prompt -> LLM -> reward -> PPO -> video
  p2p generate "<prompt>"     # prompt -> LLM, print spec, no training
  p2p train-spec <path>       # train from a JSON RewardSpec, skip LLM

Hyperparameters are fixed per env (see HalfCheetahPPOConfig). The CLI
exposes only what the user needs to drive the demo: the prompt, the
training budget, the seed, the model, and where artifacts go.
"""

from __future__ import annotations

import dataclasses
import json
import sys
from pathlib import Path
from typing import Annotated

import tyro

from prompt_to_policy.envs import halfcheetah as hc
from prompt_to_policy.llm import DEFAULT_MODEL, LLMRewardClient
from prompt_to_policy.reward import RewardSpec
from prompt_to_policy.train import HALFCHEETAH_PPO, train

DEFAULT_CACHE_DIR = "examples/cached_responses"


def _resolve_timesteps(timesteps: int | None, quick: bool) -> int:
    if timesteps is not None:
        return timesteps
    if quick:
        return HALFCHEETAH_PPO.quick_timesteps
    return HALFCHEETAH_PPO.total_timesteps


@dataclasses.dataclass
class Run:
    """Generate a reward from a prompt and train a policy end-to-end."""

    prompt: Annotated[str, tyro.conf.Positional]
    """Natural-language description of the desired behavior."""

    timesteps: int | None = None
    """Total training timesteps. Defaults to 1M; --quick overrides to 200k."""

    quick: bool = False
    """Use the 200k development budget. Ignored if --timesteps is set explicitly."""

    seed: int = 0
    """Random seed."""

    model: str = DEFAULT_MODEL
    """Anthropic model id for reward generation."""

    cache_dir: str | None = DEFAULT_CACHE_DIR
    """Directory for cached LLM responses. Pass an empty string to disable caching."""

    force_refresh: bool = False
    """Bypass the cache for this prompt and re-call the LLM."""

    run_dir: str | None = None
    """Directory for this run's artifacts. Defaults to runs/<auto-generated id>."""

    no_video: bool = False
    """Skip rollout video rendering (useful for headless runs without an OpenGL backend)."""


@dataclasses.dataclass
class Generate:
    """Call the LLM for a reward spec and print it. No training."""

    prompt: Annotated[str, tyro.conf.Positional]
    """Natural-language description of the desired behavior."""

    model: str = DEFAULT_MODEL
    """Anthropic model id."""

    cache_dir: str | None = DEFAULT_CACHE_DIR
    """Directory for cached LLM responses."""

    force_refresh: bool = False
    """Bypass the cache for this prompt."""


@dataclasses.dataclass
class TrainSpec:
    """Train a policy from a hand-written or pre-generated reward spec.

    Useful for offline reproductions and for the post's hand-written
    baselines (forward locomotion, stand still) without burning API
    spend.
    """

    spec: Annotated[Path, tyro.conf.Positional]
    """Path to a JSON file matching the RewardSpec schema."""

    prompt: str = "(no prompt — spec from file)"
    """Prompt string to record in summary.json. Has no effect on training."""

    timesteps: int | None = None
    """Total training timesteps. Defaults to 1M; --quick overrides to 200k."""

    quick: bool = False
    """Use the 200k development budget."""

    seed: int = 0
    """Random seed."""

    run_dir: str | None = None
    """Directory for this run's artifacts."""

    no_video: bool = False
    """Skip rollout video rendering."""


Command = Run | Generate | TrainSpec


def _do_generate(cmd: Generate) -> int:
    cache_dir = cmd.cache_dir if cmd.cache_dir else None
    client = LLMRewardClient(
        feature_docs=hc.FEATURE_DOCS,
        model=cmd.model,
        cache_dir=cache_dir,
    )
    gen = client.generate(cmd.prompt, force_refresh=cmd.force_refresh)
    payload = {
        "prompt": cmd.prompt,
        "model": gen.model,
        "cached": gen.cached,
        "cache_key": gen.cache_key,
        "spec": gen.spec.model_dump(),
        "usage": gen.usage,
        "estimated_cost_usd": gen.estimated_cost_usd,
    }
    print(json.dumps(payload, indent=2))
    return 0


def _do_run(cmd: Run) -> int:
    cache_dir = cmd.cache_dir if cmd.cache_dir else None
    timesteps = _resolve_timesteps(cmd.timesteps, cmd.quick)

    client = LLMRewardClient(
        feature_docs=hc.FEATURE_DOCS,
        model=cmd.model,
        cache_dir=cache_dir,
    )
    print(f"prompt    : {cmd.prompt!r}", file=sys.stderr)
    gen = client.generate(cmd.prompt, force_refresh=cmd.force_refresh)
    print(f"  cached  : {gen.cached}", file=sys.stderr)
    print(f"  cost    : ${gen.estimated_cost_usd:.4f}", file=sys.stderr)
    print(f"  spec    : {gen.spec.model_dump_json()}", file=sys.stderr)
    print(file=sys.stderr)
    print(f"training  : {timesteps} timesteps, seed={cmd.seed}", file=sys.stderr)

    result = train(
        spec=gen.spec,
        prompt=cmd.prompt,
        timesteps=timesteps,
        run_dir=Path(cmd.run_dir) if cmd.run_dir else None,
        seed=cmd.seed,
        record_video=not cmd.no_video,
    )

    print(f"\ndone in {result.train_seconds:.1f}s", file=sys.stderr)
    print(f"  final_mean_return : {result.final_mean_return:.2f}", file=sys.stderr)
    print(f"  final_mean_length : {result.final_mean_length:.0f}", file=sys.stderr)
    print(f"  run_dir           : {result.run_dir}", file=sys.stderr)
    print(f"  video             : {result.video_path}", file=sys.stderr)
    print(f"  summary           : {result.summary_path}", file=sys.stderr)
    return 0


def _do_train_spec(cmd: TrainSpec) -> int:
    timesteps = _resolve_timesteps(cmd.timesteps, cmd.quick)

    spec_text = cmd.spec.read_text()
    spec = RewardSpec.model_validate_json(spec_text)

    print(f"spec      : {cmd.spec}", file=sys.stderr)
    print(f"prompt    : {cmd.prompt!r}", file=sys.stderr)
    print(f"training  : {timesteps} timesteps, seed={cmd.seed}", file=sys.stderr)

    result = train(
        spec=spec,
        prompt=cmd.prompt,
        timesteps=timesteps,
        run_dir=Path(cmd.run_dir) if cmd.run_dir else None,
        seed=cmd.seed,
        record_video=not cmd.no_video,
    )

    print(f"\ndone in {result.train_seconds:.1f}s", file=sys.stderr)
    print(f"  final_mean_return : {result.final_mean_return:.2f}", file=sys.stderr)
    print(f"  final_mean_length : {result.final_mean_length:.0f}", file=sys.stderr)
    print(f"  run_dir           : {result.run_dir}", file=sys.stderr)
    print(f"  video             : {result.video_path}", file=sys.stderr)
    print(f"  summary           : {result.summary_path}", file=sys.stderr)
    return 0


def dispatch(cmd: Command) -> int:
    if isinstance(cmd, Run):
        return _do_run(cmd)
    if isinstance(cmd, Generate):
        return _do_generate(cmd)
    if isinstance(cmd, TrainSpec):
        return _do_train_spec(cmd)
    raise TypeError(f"unknown command: {type(cmd).__name__}")


def main(args: list[str] | None = None) -> int:
    cmd = tyro.cli(Command, args=args)
    return dispatch(cmd)


if __name__ == "__main__":
    raise SystemExit(main())
